name: cut_less
run-name: mugi
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      steps:
      - uses: actions/checkout@v3

      steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v3

      # 安装依赖
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake git ninja-build cargo