name: cut_less
run-name: mugi
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set proxy
        run: |
          echo "http_proxy=http://192.168.2.63:7897" >> $GITHUB_ENV
          echo "https_proxy=http://192.168.2.63:7897" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update
      - run: sudo apt-get install -y clang cmake git ninja-build cargo
          
          