name: cut_less
run-name: mugi
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      http_proxy: http://192.168.2.63:7897
      https_proxy: http://192.168.2.63:7897
    steps:
      - name: Checkout
        uses: http://49.235.37.217:6003/mugi/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update
      - run: sudo apt-get install -y clang cmake git ninja-build cargo
          
          