[workspace]
members = ["api_kernel","server"]

[package]
name = "cl_web_api"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server_v1"
path = "src/bin/server_v1.rs"

[[bin]]
name = "server_v2"
path = "src/bin/server_v2.rs"

[[bin]]
name = "server_v3"
path = "src/bin/server_v3.rs"

[[bin]]
name = "client"
path = "src/bin/client.rs"

[[bin]]
name = "transformer"
path = "src/bin/transformer.rs"

[dependencies]
api_kernel = {path = "./api_kernel"}
warp = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.11", features = ["json", "rustls"] }
openssl = { version = "0.10", features = ["vendored"] }
libc = "0.2.175"
decimal = "2.0"
